name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-tag-push
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Get latest image tag from ECR
        id: get-latest-tag
        run: |
          IMAGE_TAG=$(aws ecr describe-images --repository-name ${{ secrets.ECR_REPOSITORY }} --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --output text)
          echo "::set-output name=latest-tag::$IMAGE_TAG"

      - name: Get current task definition
        id: get-task-def
        run: |
          TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition ${{ secrets.TASK_DEFINITION_FAMILY }})
          echo "$TASK_DEFINITION" > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: fill-task-def
        run: |
          NEW_IMAGE="${{ steps.ecr-login.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ steps.get-latest-tag.outputs.latest-tag }}"
          jq --arg IMAGE "$NEW_IMAGE" '.taskDefinition.containerDefinitions[0].image = $IMAGE' task-definition.json > new-task-definition.json

      - name: Register a new revision of the task definition
        id: register-task-def
        run: |
          NEW_TASK_DEFINITION=$(aws ecs register-task-definition --cli-input-json file://new-task-definition.json)
          NEW_REVISION=$(echo $NEW_TASK_DEFINITION | jq -r '.taskDefinition.revision')
          echo "::set-output name=new-revision::$NEW_REVISION"

      - name: Update ECS service
        run: |
          aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER }} --service ${{ secrets.ECS_SERVICE }} --task-definition ${{ secrets.TASK_DEFINITION_FAMILY }}:${{ steps.register-task-def.outputs.new-revision }}
